//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Proyecto_LucyCaceres
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class TransitoEntities : DbContext
    {
        public TransitoEntities()
            : base("name=TransitoEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Ciudadano> Ciudadanos { get; set; }
        public virtual DbSet<MediosTransporte> MediosTransportes { get; set; }
        public virtual DbSet<Role> Roles { get; set; }
        public virtual DbSet<TipoDocumento> TipoDocumentos { get; set; }
        public virtual DbSet<TipoDocumentosxCiudadano> TipoDocumentosxCiudadanoes { get; set; }
        public virtual DbSet<TransportexCiudadano> TransportexCiudadanoes { get; set; }
        public virtual DbSet<Usuario> Usuarios { get; set; }
    }
}
