//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Proyecto_LucyCaceres
{
    using System;
    using System.Collections.Generic;
    
    public partial class TransportexCiudadano
    {
        public int id { get; set; }
        public Nullable<int> idTransporte { get; set; }
        public string ciudadanoId { get; set; }
        public string marca { get; set; }
        public string model { get; set; }
        public string placa { get; set; }
        public string ano { get; set; }
    
        public virtual Ciudadano Ciudadano { get; set; }
        public virtual MediosTransporte MediosTransporte { get; set; }
    }
}
