//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Proyecto_LucyCaceres
{
    using System;
    using System.Collections.Generic;
    
    public partial class Usuario
    {
        public string dni { get; set; }
        public string nombre { get; set; }
        public string apellido { get; set; }
        public string genero { get; set; }
        public string email { get; set; }
        public string celular { get; set; }
        public string contrasena { get; set; }
        public Nullable<int> rolId { get; set; }
    
        public virtual Role Role { get; set; }
    }
}
